package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This is a Java-based migration to ensure Flyway tracking with JPA schema generation.
 * The actual schema creation is handled by Hibernate/JPA based on entity annotations.
 */
public class V3_0__JPA_Schema extends BaseJavaMigration {
    
    private static final Logger LOGGER = LoggerFactory.getLogger(V3_0__JPA_Schema.class);
    
    @Override
    public void migrate(Context context) {
        LOGGER.info("Executing V3.0__JPA_Schema migration");
        // Empty migration as the schema is generated by Hibernate/JPA
        // This just serves as a tracking point for Flyway
        LOGGER.info("Schema initialization completed via JPA/Hibernate");
    }
} 